# Generated by Django 3.2.12 on 2022-02-16 21:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('names', '0002_auto_20220216_1502'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='derbyname',
            name='number',
        ),
        migrations.AddField(
            model_name='derbyname',
            name='number',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='names.derbynumber'),
        ),
    ]
