# Generated by Django 3.2.12 on 2022-02-16 21:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('names', '0003_auto_20220216_1505'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jersey',
            name='name',
        ),
        migrations.AddField(
            model_name='derbyname',
            name='jersey',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='names.jersey'),
        ),
    ]
