# Generated by Django 3.2.12 on 2022-02-18 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('names', '0003_alter_color_name'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='color',
            unique_together={('hex', 'pair_with')},
        ),
    ]
