# Generated by Django 3.2.12 on 2022-02-25 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('names', '0004_alter_color_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='derbynumber',
            name='cleared',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='derbyname',
            name='jersey',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='names.jersey'),
        ),
        migrations.AlterField(
            model_name='derbyname',
            name='number',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='names.derbynumber'),
        ),
    ]
