# Generated by Django 3.2.12 on 2022-02-16 21:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('names', '0005_alter_derbyname_jersey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='derbyname',
            name='jersey',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='names.jersey'),
        ),
    ]
