# Generated by Django 3.2.12 on 2022-02-16 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('names', '0006_alter_derbyname_jersey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='derbyname',
            name='meta',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='derbynumber',
            name='meta',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='jersey',
            name='meta',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='toot',
            name='meta',
            field=models.JSONField(default=dict),
        ),
    ]
